### ISSUE TITLE
你这个斗鱼服务器难道是你个人自己弄的吧！不是官方服务器！肯定不稳定

### ISSUE THREAD

**Issue by wei168hua** [x554462/danmu#1]
自己弄的服务器肯定不稳定不是官方的服务器

**Comment by zhoxife3ng** [comment]
> 自己弄的服务器肯定不稳定不是官方的服务器

是的，这只是爬取弹幕的客户端，不是什么服务器。是爬取了网页端的直播页面，通过分析弹幕接口写出来的获取实时弹幕的小demo
