### ISSUE TITLE
问下弹幕协议添加问题

### ISSUE THREAD

**Issue by dfaofeng** [x554462/danmu#2]
![QQ截图20200507180508](https://user-images.githubusercontent.com/14891398/81282174-63f4d680-908d-11ea-914c-3a81d6989b9c.png)
上面是不是和下面一一对应的呢？
![image](https://user-images.githubusercontent.com/14891398/81282264-7f5fe180-908d-11ea-93cf-b2239e73ee42.png)这个值就是最后打印的信息是吧?

**Comment by zhoxife3ng** [comment]
> ![QQ截图20200507180508](https://user-images.githubusercontent.com/14891398/81282174-63f4d680-908d-11ea-914c-3a81d6989b9c.png)
> 上面是不是和下面一一对应的呢？
> ![image](https://user-images.githubusercontent.com/14891398/81282264-7f5fe180-908d-11ea-93cf-b2239e73ee42.png)这个值就是最后打印的信息是吧?

1、是一一对应的
2、判断到当前类型为弹幕信息，将匹配到的弹幕文本发送给chan，由上层handle输出

**Comment by dfaofeng** [comment]
![image](https://user-images.githubusercontent.com/14891398/81294250-31ed6f80-90a1-11ea-8e74-91adc4e59c22.png)
![image](https://user-images.githubusercontent.com/14891398/81294273-39147d80-90a1-11ea-9ec1-2117c51ae0d7.png)
但是我改了下输出类型就完全没有输出了....

**Comment by zhoxife3ng** [comment]
> ![image](https://user-images.githubusercontent.com/14891398/81294250-31ed6f80-90a1-11ea-8e74-91adc4e59c22.png)
> ![image](https://user-images.githubusercontent.com/14891398/81294273-39147d80-90a1-11ea-9ec1-2117c51ae0d7.png)
> 但是我改了下输出类型就完全没有输出了....

嗯，因为没有收到这种类型的消息推送，推送大部分都是“弹幕消息”类型，你可以在if外面打印data看一下

**Comment by dfaofeng** [comment]
> > ![image](https://user-images.githubusercontent.com/14891398/81294250-31ed6f80-90a1-11ea-8e74-91adc4e59c22.png)
> > ![image](https://user-images.githubusercontent.com/14891398/81294273-39147d80-90a1-11ea-9ec1-2117c51ae0d7.png)
> > 但是我改了下输出类型就完全没有输出了....
> 
> 嗯，因为没有收到这种类型的消息推送，推送大部分都是“弹幕消息”类型，你可以在if外面打印data看一下

我看了下,有正常的弹幕啊...
![image](https://user-images.githubusercontent.com/14891398/81305155-93690a80-90b0-11ea-8c00-1802346f5b21.png)
![image](https://user-images.githubusercontent.com/14891398/81305269-b4316000-90b0-11ea-8441-c9ed2d94d5cc.png)
但是最后print的信息是
![image](https://user-images.githubusercontent.com/14891398/81305418-e5119500-90b0-11ea-821a-9014529a9d3f.png)

**Comment by zhoxife3ng** [comment]
> > > ![image](https://user-images.githubusercontent.com/14891398/81294250-31ed6f80-90a1-11ea-8e74-91adc4e59c22.png)
> > > ![image](https://user-images.githubusercontent.com/14891398/81294273-39147d80-90a1-11ea-9ec1-2117c51ae0d7.png)
> > > 但是我改了下输出类型就完全没有输出了....
> > 
> > 
> > 嗯，因为没有收到这种类型的消息推送，推送大部分都是“弹幕消息”类型，你可以在if外面打印data看一下
> 
> 我看了下,有正常的弹幕啊...
> ![image](https://user-images.githubusercontent.com/14891398/81305155-93690a80-90b0-11ea-8c00-1802346f5b21.png)
> ![image](https://user-images.githubusercontent.com/14891398/81305269-b4316000-90b0-11ea-8441-c9ed2d94d5cc.png)
> 但是最后print的信息是
> ![image](https://user-images.githubusercontent.com/14891398/81305418-e5119500-90b0-11ea-821a-9014529a9d3f.png)

正常弹幕的类型是RecvTypeChatMsg，其它类型是不是正常弹幕，比如RecvTypeUserEnter（用户进入房间通知）、RecvTypeShareRoom（分享房间通知）...，如果你只想看弹幕消息的话，用RecvTypeChatMsg即可

**Comment by dfaofeng** [comment]
假如我要 "lv{} 用户名: 内容"打印,应该改那些代码呢?
